# This docker compose file is used to run Dragon Bot Z
#
# Authors: Lahcène Belhadi <lahcene.belhadi@gmail.com>
version: '3.9'
services:
  # Character service
  character-service:
    image: dbz-character-service
    container_name: dbz-character-service
    ports:
      - 58180:8080
    depends_on:
      - character-database
    restart: always
    environment:
      DBZ_PG_SUPERUSER_PASS: "${DBZ_PG_SUPERUSER_PASS}"

  character-database:
    image: postgres:16
    container_name: dbz-character-database
    volumes:
      - dbz-character-database-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DBZ_PG_SUPERUSER_PASS}"

  # Portal service
  portal-service:
    image: dbz-portal-service
    container_name: dbz-portal-service
    ports:
      - 58181:8080
    depends_on:
      - portal-database
    restart: always
    environment:
      DBZ_PG_SUPERUSER_PASS: "${DBZ_PG_SUPERUSER_PASS}"

  portal-database:
    image: postgres:16
    container_name: dbz-portal-database
    volumes:
      - dbz-portal-database-volume:/var/lib/postgresql/data
    ports:
      - 5433:5433
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DBZ_PG_SUPERUSER_PASS}"

  # Summon service
  summon-service:
    image: dbz-summon-service
    container_name: dbz-summon-service
    ports:
      - 58182:8080
    depends_on:
      - character-service
      - portal-service
    restart: always

  # Player collecion service
  player-collection-service:
    image: dbz-player-collection-service
    container_name: dbz-player-collection-service
    ports:
      - 58183:8080
    restart: always
    environment:
      DBZ_PG_SUPERUSER_PASS: "${DBZ_PG_SUPERUSER_PASS}"

  player-collection-database:
    image: postgres:16
    container_name: dbz-player-collection-database
    volumes:
      - dbz-player-collection-database-volume:/var/lib/postgresql/data
    ports:
      - 5434:5434
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DBZ_PG_SUPERUSER_PASS}"

# The volumes are all external volumes and must be created using
# `docker volume create` command
volumes:
  # Character database volume
  dbz-character-database-volume:
    external: true
  
  # Portal database volume
  dbz-portal-database-volume:
    external: true

  # Player collection volume
  dbz-player-collection-database-volume:
    external: true
